### ISSUE TITLE
module is enforcing using deprecated module

### ISSUE THREAD

**Issue by ed-mt** [example42/puppet-activemq#7]
[root@puppet manifests]# puppet module install example42-activemq
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'example42-activemq' (latest)
  Dependency 'example42-firewall' (v2.1.3) would overwrite /etc/puppetlabs/code/environments/production/modules/firewall
    Currently, 'puppetlabs-firewall' (v1.7.1) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module

furthermore, the example42-firewall module states the following:

DEPRECATION NOTICE

This module is no more actively maintained and will hardly be updated.

Please find an alternative module from other authors or consider Tiny Puppet as replacement.

If you want to maintain this module, contact Alessandro Franceschi

**Comment by alvagante** [comment]
Just pushed to the forge an updated version without dependencies. Thanks for reporting.
